.TH SLIDESSORTER 1 "Jan 2017" "version 0.1" "User Manuals"
.SH "NAME"
Slides Sorter \- GUI for Latex Beamer slidedecks sorting and re-organization
.SH "SYNOPSIS"
.B slidessorter [file1] [file2] ...
.SH "DESCRIPTION"
.B Slides sorter is a small utility that:

- opens a PDF file
.br
- attempts to open the matching Beamer Latex source
.br
- let you re-arrange your slides (re-order, remove some, etc)
.br
- save the resulting PDF **and updated Beamer source**.
.br

You can then directly use the edited PDF or better,
re-compile your Beamer source to get right all the links 
and navigation bar.

Slides Sorter is heavily based on pdfshuffler by Konstantinos Poulios.

.SH "OPTIONS"
Currently Slides Sorter doesn't receive any options.
.SH "FILES"
Currently Slides Sorter has no configuration file.
.SH "ENVIRONMENT"
All gtk related enviroment variables.
.SH "DIAGNOSTICS"
Common python and gtk diagnostics.
.SH "AUTHOR"
Séverin Lemaignan <severin@guakamole.org>
Konstantinos Poulios <logari81@gmail.com>

